# Generated by Codex on 2026-06-30

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxcalculation',
            old_name='total_income',
            new_name='gross_income',
        ),
        migrations.RenameField(
            model_name='taxcalculation',
            old_name='total_expenses',
            new_name='deductible_expenses',
        ),
        migrations.RenameField(
            model_name='taxcalculation',
            old_name='taxable_profit',
            new_name='taxable_income',
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='tax_year',
            field=models.PositiveIntegerField(default=2027),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='tax_before_rebates',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='rebate_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='bracket_description',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
